<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <Target Name="PrintDefines" BeforeTargets="Build" Condition="'$(ChaosConfigurationsImported)'==''">
    <Message Importance="High" Text="[$(AssemblyName)] Defines: $(DefineConstants)" />
  </Target>

  <Choose>
    <When Condition="'$(ChaosConfigurationsImported)'==''">

      <PropertyGroup Condition="'$(Platform)' == ''">
        <Platform>AnyCPU</Platform>
      </PropertyGroup>
      <PropertyGroup Condition="'$(Configuration)' == ''">
        <Configuration>Debug</Configuration>
      </PropertyGroup>

      <PropertyGroup Condition="'$(Configuration)' == 'Debug' And '$(DefineConstants)' != ''">
        <DefineConstants>$(DefineConstants);DEBUG</DefineConstants>
      </PropertyGroup>
      <PropertyGroup Condition="'$(Configuration)' == 'Debug' And '$(DefineConstants)' == ''">
        <DefineConstants>DEBUG</DefineConstants>
      </PropertyGroup>

      <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <Optimize>false</Optimize>
        <DebugType>full</DebugType>
        <DebugSymbols>true</DebugSymbols>
      </PropertyGroup>
      <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <Optimize>true</Optimize>
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
      </PropertyGroup>

      <PropertyGroup>
        <ChaosConfigurationsImported>true</ChaosConfigurationsImported>
      </PropertyGroup>

    </When>
  </Choose>

</Project>
