<Project>

  <Import Project="./SetOs.targets" />

  <PropertyGroup Condition="'$(OS)'!='Windows'">
    <SkipCompilerExecution>true</SkipCompilerExecution>
    <SkipDefaultCompileItems>true</SkipDefaultCompileItems>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <PlatformNotSupported>true</PlatformNotSupported>
  </PropertyGroup>

  <Import Project="SkipUnsupportedPlatform.targets" />

</Project>
